config/routes.rb
SmartSchool::Application.routes.draw do
  devise_for :schools
  devise_for :admins
  devise_for :students
  devise_for :teachers
  
  namespace :school do
    root to: 'application#home'

    resources :subjects
    resources :teachers
    resources :students
    resources :groups
  end

  namespace :teacher do
    root to: 'application#home'
  end

  namespace :student do
    root to: 'application#home'
  end

  namespace :admin do
    root to: 'application#home'
  end

  root to: 'application#home'
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :school

  has_many :group_students
  accepts_nested_attributes_for :group_students, :allow_destroy => true

  has_many :students, through: :group_students

  has_many :group_subjects
  accepts_nested_attributes_for :group_subjects, :allow_destroy => true

  has_many :subjects, through: :group_subjects
  has_many :teachers, through: :subjects

  attr_protected :id

  validates :name, presence: true
end

app/models/school.rb
class School < User

  has_many :subjects

  has_many :groups

  has_many :enrollments
  has_many :students, through: :enrollments

  has_many :jobs
  has_many :teachers, through: :jobs
  
  def admin?
    false
  end

  def school?
    true
  end

  def student?
    false
  end

  def teacher?
    false
  end
end

app/controllers/school/application_controller.rb
class School::ApplicationController < ApplicationController
  before_filter :authenticate_school!

  def home
    
  end
end

app/controllers/school/groups_controller.rb
class School::GroupsController < School::ApplicationController

  def index
    @groups = current_school.groups
  end

  def update
    @group = current_school.groups.find(params[:id])
    binding.pry
    if @group.update_attributes(params[:group])
      redirect_to school_group_path(@group), success: I18n.t('messages.update.success', model: 'Turma')
    else
      flash.now[:error] = I18n.t('messages.update.error', model: 'Turma')
      render 'edit'
    end
  end

  def create
    @group = Group.new(params[:group])
    @group.school_id = current_school.id
    if @group.save
      redirect_to school_group_path(@group), success: I18n.t('messages.update.success', model: 'Turma')
    else
      flash.now[:error] = I18n.t('messages.create.error', model: 'Turma')
      render 'new'
    end
  end

  def new
    @group = Group.new
  end

  def show
    @group = current_school.groups.find(params[:id])
  end

  def edit
    @group = current_school.groups.find(params[:id])
  end
end

app/controllers/school/students_controller.rb
# coding: utf-8
class School::StudentsController < School::ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(params[:student])
    @student.school_id = current_school.id
    @student.password = '123qwe'
    @student.password_confirmation = '123qwe'
    if @student.save
      flash[:alert] = "Senha temporária automaticamente: '123qwe'"
      redirect_to school_student_path(@student), success: I18n.t('messages.update.success', model: 'Aluno')
    else
      flash.now[:error] = I18n.t('messages.create.error', model: 'Aluno')
      render 'new'
    end
  end

  def show
    @student = current_school.students.find(params[:id])
  end

  def edit
    @student = current_school.students.find(params[:id])
  end

  def update
    @student = current_school.students.find(params[:id])
    if @student.update_attributes(params[:student])
      redirect_to school_student_path(@student), success: I18n.t('messages.update.success', model: 'Aluno')
    else
      flash.now[:error] = I18n.t('messages.update.error', model: 'Aluno')
      render 'edit'
    end
  end

  def index
    @students = current_school.students
  end
end

app/controllers/school/subjects_controller.rb
#coding: utf-8
class School::SubjectsController < School::ApplicationController
  
  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params[:subject])
    @subject.school = current_school
    if @subject.save
      redirect_to school_subject_path(@subject), success: I18n.t('messages.update.success', model: 'Matéria')
    else
      flash.now[:error] = I18n.t('messages.create.error', model: 'Matéria')
      render 'new'
    end
  end

  def show
    @subject = current_school.subjects.find(params[:id])
  end

  def edit
    @subject = current_school.subjects.find(params[:id])
  end

  def update
    @subject = current_school.subjects.find(params[:id])
    if @subject.update_attributes(params[:subject])
      redirect_to school_subject_path(@subject), success: I18n.t('messages.update.success', model: 'Matéria')
    else
      flash.now[:error] = I18n.t('messages.update.error', model: 'Matéria')
      render 'edit'
    end
  end

  def index
    @subjects = current_school.subjects
  end
end

app/controllers/school/teachers_controller.rb
# coding: utf-8
class School::TeachersController < School::ApplicationController
  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(params[:teacher])
    @teacher.schools << current_school
    @teacher.password = '123qwe'
    @teacher.password_confirmation = '123qwe'
    if @teacher.save
      flash[:alert] = "Senha gerada automaticamente: '123qwe'"
      redirect_to school_teacher_path(@teacher), success: I18n.t('messages.update.success', model: 'Professor')
    else
      flash.now[:error] = I18n.t('messages.create.error', model: 'Professor')
      render 'new'
    end
  end

  def show
    @teacher = current_school.teachers.find(params[:id])
  end

  def edit
    @teacher = current_school.teachers.find(params[:id])
  end

  def update
    @teacher = current_school.teachers.find(params[:id])
    if @teacher.update_attributes(params[:teacher])
      redirect_to school_teacher_path(@teacher), success: I18n.t('messages.update.success', model: 'Professor')
    else
      flash.now[:error] = I18n.t('messages.update.error', model: 'Professor')
      render 'edit'
    end
  end

  def index
    @teachers = current_school.teachers
  end
end

app/helpers/school/application_helper.rb
module School::ApplicationHelper
end

app/helpers/school/groups_helper.rb
module School::GroupsHelper
end

app/helpers/school/students_helper.rb
module School::StudentsHelper
end

app/helpers/school/subjects_helper.rb
module School::SubjectsHelper
end

app/helpers/school/teachers_helper.rb
module School::TeachersHelper
end

app/views/school/groups/_form.html.haml
= form_for [:school, @group], html: { method: (@group.new_record? ? :post : :put) } do |f|
  
  %p= f.label :name
  %p= f.text_field :name

  %p= label_tag :subject, t('actions.subjects')
  #subjects_list
    - f.object.group_subjects.each do |subject|
      = f.fields_for :group_subjects, subject do |f_s|
        %p
          = f_s.object.subject.name
          = f_s.select :teacher_id, current_school.teachers.collect { |t| [t.name, t.id] }, prompt: 'Selecione'
  %p
    = select_tag :subject, options_from_collection_for_select(current_school.subjects - f.object.subjects, :id, :name), prompt: 'Selecione'
    = link_to 'Adicionar a turma', 'javascript:;', onclick: "add_to_group('subject')"

  %p= label_tag :student, t('actions.alunos')
  #students_list
    - f.object.students.each do |student|
      %p= student.name
  %p
    = select_tag :student, options_from_collection_for_select(current_school.students - f.object.students, :id, :name), prompt: 'Selecione'
    = link_to 'Adicionar a turma', 'javascript:;', onclick: "add_to_group('student')"
  
  = f.submit t('actions.confirm')

:javascript
  function add_to_group(id){
    current_form = $('#' + id)
    if( $('#'+id).val() != null ){
      current_form.append('<input type="hidden" name="group[group_' + id + 's_attributes][][' + id + '_id]" value="' + $('#'+id).val() + '">');
      if(id == 'subject'){
        element = '<p>'+$('#'+id).find(':selected').text()
        element = element + '<select name="group[group_subjects_attributes][][teacher_id]">#{current_school.teachers.collect {|t| '<option value="' + t.id.to_s + '">' + t.name + '</option>'} }</select>'
        element = element + '</p>'
        $('#'+id+'s_list').append(element)
      }else{
        $('#'+id+'s_list').append('<p>'+$('#'+id).find(':selected').text()+'</p>');
      }
      $('#'+id).find(':selected').remove()
    }else{
      if(id == 'subject'){
        alert('É preciso escolher uma matéria para adicionar')
      }else{
        alert('É preciso escolher um aluno para adicionar')
      }
    }
  }

app/views/school/groups/_group.html.haml
%tr
  %td= link_to group.name, school_group_path(group)
  %td= link_to t('actions.edit', model: 'Turma'), edit_school_group_path(group)

app/views/school/groups/edit.html.haml
= link_to t('actions.back'), school_groups_path

= render 'form'

app/views/school/groups/index.html.haml
= link_to t('actions.new', model: 'Turma'), new_school_group_path
%table
  %thead
    %tr
      %th= t('activerecord.attributes.group.name')
  %tbody
    = render @groups

app/views/school/groups/new.html.haml
= link_to t('actions.back'), school_groups_path

= render 'form'

app/views/school/groups/show.html.haml
= link_to t('actions.edit', model: 'Turma'), edit_school_group_path(@group)

.show
  %p= @group.name